### ISSUE TITLE
Boolean Flag for Access Logs Config in ALB

### ISSUE THREAD

**Issue by essanpupil** [traveloka/terraform-aws-alb-single-listener#22]
### Description
Sometime we does not want to enable access logs for our ALB. We need to have flag variable to disable access logs.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration Changes

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
```

### References

* #0000

**Comment by sumodirjo** [comment]
Hi @essanpupil ,
I'm guessing you might not want to enable logging in testing or staging environment. Do you mind to elaborate further what you mention on the description "Sometime we does not want to enable access logs for our ALB.". Thank you.

**Comment by essanpupil** [comment]
Actually, the more accurate term for our case is, "we are not aware about the benefit of having access log". But after explanation from in our slack chat, we decide to create s3 bucket to store access log. I will close this issue since it is not related anymore.
